/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#f0e8db",
        "on-tertiary-fixed-variant": "#554020",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f5f1ea",
        "outline-variant": "#c4c8bc",
        "surface-container-highest": "#e4e0d8",
        "on-tertiary-fixed": "#221a05",
        primary: "#5c8c6a",
        error: "#b83230",
        "secondary-fixed-dim": "#d4ccbf",
        secondary: "#6b6358",
        "on-surface": "#2e3230",
        "on-primary-container": "#d8f0de",
        "tertiary-fixed": "#f8e0a8",
        "tertiary-container": "#c4a66a",
        "surface-tint": "#5c8c6a",
        "surface-container": "#f0ece4",
        "on-primary": "#ffffff",
        "primary-fixed": "#c8e8d0",
        "primary-fixed-dim": "#8ecf9e",
        "on-tertiary-container": "#554020",
        "on-surface-variant": "#4a4e4a",
        "surface-variant": "#e4e0d8",
        "on-secondary-fixed": "#1e1a13",
        "on-secondary-container": "#5e5548",
        surface: "#faf6f0",
        "on-error-container": "#690005",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        background: "#faf6f0",
        "surface-container-high": "#eae6de",
        "on-secondary-fixed-variant": "#4a4538",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f5f0e8",
        "secondary-container": "#f0e8db",
        "inverse-primary": "#8ecf9e",
        "on-primary-fixed": "#002110",
        "inverse-surface": "#2e3230",
        "error-container": "#ffdad8",
        "surface-bright": "#faf6f0",
        "primary-container": "#8fb89e",
        "on-primary-fixed-variant": "#2a6038",
        "on-background": "#2e3230",
        outline: "#74796e",
        tertiary: "#705c30",
        "surface-dim": "#dbd7cf",
        "tertiary-fixed-dim": "#dcc48e",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        lg: "24px",
        sm: "8px",
        md: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        xs: "4px",
        gutter: "16px",
        xl: "48px",
      },
      fontFamily: {
        "headline-lg": ["Literata", "serif"],
        "body-md": ["Nunito Sans", "sans-serif"],
        "label-sm": ["Nunito Sans", "sans-serif"],
        "headline-lg-mobile": ["Literata", "serif"],
        "label-md": ["Nunito Sans", "sans-serif"],
        "display-lg": ["Literata", "serif"],
        "headline-md": ["Literata", "serif"],
        "body-lg": ["Nunito Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      screens: {
        xs: "360px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
